Magere\Status\Model\Status:
  type: entity
  table: status
  options:
    comment: Статусы
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    name:
     type: string
     length: 255
    mnemo:
      type: string
      length: 50
      options:
        default: ''
    entityId:
      type: integer
      options:
        unsigned: true
    hidden:
      type: integer
      length: 1
      nullable: false
      options:
        default: 0
        comment: Доступні значення 0 (Не показывать) / 1 (показывать статус)
    remove:
      type: integer
      length: 1
      nullable: false
      options:
        default: 1
        comment: Чи можна видаляти значення 0, 1
    automatically:
      type: string
      length: 1
      nullable: false
      options:
        default: 0
        comment: Ставится ли данный статус автоматически 0, 1
    color:
      type: string
      length: 50
      options:
        default: ''
        comment: Цвет
  oneToOne:
    rule:
      targetEntity: Magere\Status\Model\Rule
      mappedBy: status
  oneToMany:
    mail:
      targetEntity: Magere\Mail\Model\Mail
      mappedBy: status
    #progress:
    #  targetEntity: Magere\Status\Model\Progress
    #  mappedBy: status

    warranty:
      targetEntity: Magere\Warranty\Model\Warranty
      mappedBy: status
    workWarranty:
      targetEntity: Magere\Warranty\Model\Warranty
      mappedBy: workStatus
    logistics:
      targetEntity: Magere\Logistics\Model\Logistics
      mappedBy: status
    logisticsWith:
      targetEntity: Magere\Logistics\Model\Logistics
      mappedBy: statusWith
    orderSale:
      targetEntity: Magere\OrderSale\Model\OrderSale
      mappedBy: status
    clients:
      targetEntity: Magere\Clients\Model\Clients
      mappedBy: status
    shopSpares:
      targetEntity: Magere\Spares\Model\ShopSpares
      mappedBy: status
    shopSparesItem:
      targetEntity: Magere\Spares\Model\ShopSparesItem
      mappedBy: status
    shopPromotionalProducts:
      targetEntity: Magere\PromotionalProducts\Model\ShopPromotionalProducts
      mappedBy: status
    shopPromotionalProductsItem:
      targetEntity: Magere\PromotionalProducts\Model\ShopPromotionalProductsItem
      mappedBy: status
  manyToOne:
    entity:
      targetEntity: Magere\Entity\Model\Entity
      inversedBy: status
      joinColumn:
        name: entityId
        referencedColumnName: id
  manyToMany:
    workflow:
      targetEntity: Magere\Status\Model\Status
      joinTable:
        name: status_workflow
        joinColumns:
          statusId:
            referencedColumnName: id
        inverseJoinColumns:
          nextStatusId:
            referencedColumnName: id