Agere\Status\Model\Progress:
  type: entity
  repositoryClass: Agere\Status\Model\Repository\ProgressRepository
  table: status_progress
  options:
    comment: Status Progress
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
      options:
        unsigned: true
    modifiedAt:
     name: modifiedAt
     type: datetime
    snippet:
      type: text
      unique: false
      nullable: false
      length: 65535
      options:
        default: ''
    itemId:
      type: integer
      options:
       unsigned: true
  manyToOne:
    status:
      targetEntity: Agere\Status\Model\Status
      joinColumn:
        name: statusId
        referencedColumnName: id
    module:
      targetEntity: Agere\Module\Model\Module
      joinColumn:
        name: moduleId
        referencedColumnName: id
