Agere\Status\Model\Status:
  type: entity
  repositoryClass: Agere\Status\Model\Repository\StatusRepository
  table: status
  options:
    comment: Статусы
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    name:
     type: string
     length: 255
    mnemo:
      type: string
      length: 50
      options:
        default: ''
    moduleId:
      type: integer
      options:
        unsigned: true
    hidden:
      type: integer
      length: 1
      nullable: true
      options:
        default: 0
        comment: Доступні значення 0 (Не показывать) / 1 (показывать статус)
    remove:
      type: integer
      length: 1
      nullable: true
      options:
        default: 1
        comment: Чи можна видаляти значення 0, 1
    automatically:
      type: string
      length: 1
      nullable: true
      options:
        default: 0
        comment: Ставится ли данный статус автоматически 0, 1
    color:
      type: string
      length: 50
      nullable: true
      options:
        default: ''
        comment: Цвет
  manyToOne:
    module:
      targetEntity: Agere\Module\Model\Module
      inversedBy: status
      joinColumn:
        name: moduleId
        referencedColumnName: id
  manyToMany:
    workflow:
      targetEntity: Agere\Status\Model\Status
      joinTable:
        name: status_workflow
        joinColumns:
          statusId:
            referencedColumnName: id
        inverseJoinColumns:
          nextStatusId:
            referencedColumnName: id
