Popov\ZfcStatus\Model\Status:
  type: entity
  table: status
  options:
    comment: Статусы
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    name:
     type: string
     length: 255
    mnemo:
      type: string
      length: 50
      options:
        default: ''
    entityId:
      type: integer
      options:
        unsigned: true
    hidden:
      type: integer
      length: 1
      nullable: false
      options:
        default: 0
        comment: Доступні значення 0 (Не показывать) / 1 (показывать статус)
    remove:
      type: integer
      length: 1
      nullable: false
      options:
        default: 1
        comment: Чи можна видаляти значення 0, 1
    automatically:
      type: string
      length: 1
      nullable: false
      options:
        default: 0
        comment: Ставится ли данный статус автоматически 0, 1
    color:
      type: string
      length: 50
      options:
        default: ''
        comment: Цвет
  oneToOne:
    rule:
      targetEntity: Popov\ZfcStatus\Model\Rule
      mappedBy: status
  oneToMany:
    mail:
      targetEntity: Magere\Mail\Model\Mail
      mappedBy: status
    #progress:
    #  targetEntity: Popov\ZfcStatus\Model\Progress
    #  mappedBy: status

  manyToOne:
    entity:
      targetEntity: Magere\Entity\Model\Entity
      inversedBy: status
      joinColumn:
        name: entityId
        referencedColumnName: id
  manyToMany:
    workflow:
      targetEntity: Popov\ZfcStatus\Model\Status
      joinTable:
        name: status_workflow
        joinColumns:
          statusId:
            referencedColumnName: id
        inverseJoinColumns:
          nextStatusId:
            referencedColumnName: id